### PR TITLE
Added SMD tag to SMD components for centroid data output.

### PR DESCRIPTION
**Pull request by kyle-goodwin**
Centroid data needed to get the boards assembled with SMD components. Added the tag to the library footprints and updated board from library.

### CODE REVIEW

**Comment by hydromisc** [comment]
Thanks, helpful. Perhaps also commit the centroid file to `board/fab`?

**Comment by kyle-goodwin** [comment]
I didn't include the output file because they sometimes need to be adjusted per board house. The place I usually use doesn't have many of the digikey parts in your BOM. Once I have a viable BOM and centroid file for a particular fab house I'll commit that to the fab directory.

**Comment by hydromisc** [comment]
Cool, reasonable. Let me know if you have any questions about second sources, since almost everything on that board should have some.

**Comment by kyle-goodwin** [comment]
I usually use JLCPCB for prototype stuff. They are extremely inexpensive but have a limited inventory. There were a couple items in the BOM that were going to be problematic. If you want to discuss it further we can do so over email or discord or whatever you like.

**Comment by hydromisc** [comment]
I'd suggest opening an issue if you have questions about second sources, to keep all the information in one place for anyone else reading. Also feel free to email me (hydromisc@gmail.com), though.

**Pull request merged**
